FROM continuumio/miniconda3 as builder

LABEL maintainer="Anton Korosov <anton.korosov@nersc.no>"
LABEL purpose="Python libs for developing and running Nansat"

ARG PYTHON_VERSION=3.7

# Install build tools
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    gcc \
    wget

COPY environment.yml /tmp/environment.yml
RUN sed -i -E "s/^(\s+- python=).*$/\1${PYTHON_VERSION}/" /tmp/environment.yml

RUN conda config --set channel_priority strict \
&&  conda env create -f /tmp/environment.yml

RUN wget -nc -nv -P /usr/share/MOD44W https://github.com/nansencenter/mod44w/raw/master/MOD44W.tgz && \
    tar -xzf /usr/share/MOD44W/MOD44W.tgz -C /usr/share/MOD44W/

RUN conda install conda-pack && \
    conda-pack -n environment -o /tmp/env.tar && \
    mkdir /venv && tar -C /venv -xf /tmp/env.tar && \
    /venv/bin/conda-unpack

FROM debian:buster

COPY --from=builder /usr/share/MOD44W /usr/share/MOD44W
COPY --from=builder /venv /venv

ENV VIRTUAL_ENV='/venv'
ENV PATH="$VIRTUAL_ENV/bin:$PATH"
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/src
ENV MOD44WPATH=/usr/share/MOD44W

RUN python -c 'import pythesint; pythesint.update_all_vocabularies()'

WORKDIR /src
