---
name: environment
channels:
  - defaults
dependencies:
  - python=3.8.18
  - conda=23.9.0

  - cartopy=0.18.0
  - coverage=5.5
  - coveralls=3.2.0
  - gdal=3.6.2
  - ipython=8.12.2
  - matplotlib=3.7.2
  - mock=4.0.3
  - netcdf4=1.6.2
  - nose=1.3.7
  - numpy=1.24.3
  - pillow=10.0.1
  - pip=23.3
  - PyYAML=5.4.1
  - scipy=1.10.1
  - setuptools=68.0.0
  - urllib3=1.26.18
  - pip:
      - pythesint==1.6.6
